<?= $this->insert('overall/header') ?>
  <body>    
    <?= $this->insert('overall/navmovil')?>
    <!-- Navbar-->
    <!-- Remove "navbar-sticky" class to make navigation bar scrollable with the page.-->
   <?= $this->insert('overall/topnav')?>
    <!-- Off-Canvas Wrapper-->
    <div class="offcanvas-wrapper">
      <!-- Page Content-->
      <div class="container padding-top-3x padding-bottom-3x mb-1"><img class="d-block m-auto" src="views/backend/img/404_art.jpg" style="width: 100%; max-width: 550px;" alt="404">
        <div class="padding-top-1x mt-2 text-center">
          <h3>404 ERROR</h3>
          <p>Controlador no encontrado <a href="index-2.html">Ir a la pagina de inicio</a></p>
        </div>
      </div>
      <?= $this->insert('overall/inner_footer')?>
    <?= $this->insert('overall/footer')?>
  </body>
</html>
