<?php require'core/models/User.php';
$obj = new Home;
    $us = $obj->usuarios();
  $cat=new User;
    $c = $cat->cate(); ?>
 <header class="navbar navbar-sticky">
      <!-- Search-->
      <form class="site-search" method="get">
        <input type="text" name="site_search" placeholder="Encuentra lo que buscas...">
        <div class="search-tools"><span class="clear-search">Limpiar</span><span class="close-search"><i class="icon-cross"></i></span></div>
      </form>
      <div class="site-branding">
        <div class="inner">
          <!-- Off-Canvas Toggle (#mobile-menu)--><a class="offcanvas-toggle menu-toggle" href="#mobile-menu" data-toggle="offcanvas"></a>
          <!-- Site Logo--><a class="site-logo" href="index-2.html"><img src="views/backend/img/logo/logo.png" alt="Unishop"></a>
        </div>
      </div>
      <!-- Main Navigation-->
      <nav class="site-menu">
        <ul>
          <li class="has-megamenu"><a href="home/"><span>Inicio</span></a>
          </li>
          <li><a href="#"><span>Productos</span></a></li>
          <li class="has-megamenu"><a href="#"><span>Menu de categorias</span></a>
            <ul class="mega-menu">
              <li><span class="mega-menu-title">Categorias <b style="color: red;">TOP</b></span>
                <ul class="sub-menu">
                <?php                   
                 for($a = 0; $a < count($c); $a++){ ?> 

                <?=  $cate= '<li><a href="'.$c[$a]['Nombre_categ'].'">'.$c[$a]['Nombre_categ'].'</a></li>';
                 ?>

                 <?php
                 }
                  ?>
                </ul>
              </li>
              <li><span class="mega-menu-title">Productos <b style="color: red;">TOP</b></span>
                <ul class="sub-menu">
                  <li><a href="#">Junior's Shop</a></li>
                  <li><a href="#">Swim Shop</a></li>
                  <li><a href="#">Athletic Shop</a></li>
                  <li><a href="#">Outdoor Shop</a></li>
                  <li><a href="#">Luxury Shop</a></li>
                  <li><a href="#">Accessories Shop</a></li>
                </ul>
              </li>
              <li>
                <section class="promo-box" style="background-image: url(views/backend/img/banners/02.jpg);"><span class="overlay-dark" style="opacity: .4;"></span>
                  <div class="promo-box-content text-center padding-top-2x padding-bottom-2x">
                    <h4 class="text-light text-thin text-shadow">New Collection of</h4>
                    <h3 class="text-bold text-light text-shadow">Sunglasses</h3><a class="btn btn-sm btn-primary" href="#">Shop Now</a>
                  </div>
                </section>
              </li>
              <li>
                <section class="promo-box" style="background-image: url(views/backend/img/banners/03.jpg);">
                  <!-- Choose between .overlay-dark (#000) or .overlay-light (#fff) with default opacity of 50%. You can overrride default color and opacity values via 'style' attribute.--><span class="overlay-dark" style="opacity: .45;"></span>
                  <div class="promo-box-content text-center padding-top-2x padding-bottom-2x">
                    <h3 class="text-bold text-light text-shadow">Limited Offer</h3>
                    <h4 class="text-light text-thin text-shadow">save up to 50%!</h4><a class="btn btn-sm btn-primary" href="#">Learn More</a>
                  </div>
                </section>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- Toolbar-->
      <div class="toolbar">
        <div class="inner">
          <div class="tools">
            <div class="search"><i class="icon-search"></i></div>
            <?php if(isset($_SESSION[SESS_APP_ID])): ?>
              

              <?= '<div class="account"><a href="perfil/"></a><i class="icon-head"></i>
              <ul class="toolbar-dropdown">
                <li class="sub-menu-user">
                  <div class="user-ava"><img src="'.$us[0]['Img_users'].'" alt="'.$us[0]['Nombre'].'">
                  </div>
                  <div class="user-info">
                    <h6 class="user-name">'.$us[0]['Nombre'].'</h6><span class="text-xs text-muted">'.$us[0]['Puntos'].' puntos</span>
                  </div>
                </li>
                  <li><a href="perfil/">Mi perfil</a></li>
                  <li><a href="list/">Lista de prodcutos</a></li>
                  <li><a href="favorite/">Favoritos</a></li>
                <li class="sub-menu-separator"></li>
                <li><a href="logout/"> <i class="icon-unlock"></i>Cerrar sesion</a></li>
              </ul>
            </div>
            <div class="cart" id="noti">
            <a href="cart.html"></a><i class="icon-bag"></i><span class="count" id="countt"></span><span class="subtotal" id="subtotall"></span><div class="toolbar-dropdown">
            <div id="bodynoti"></div>

            <div class="toolbar-dropdown-group">
                  <div class="column"><span class="text-lg">Total:</span></div>
                 <div class="column text-right"><span class="text-lg text-medium" id="totall"></span></div>
                </div>
                <div class="toolbar-dropdown-group">
                  <div class="column"><a class="btn btn-sm btn-block btn-secondary" href="cart.html">View Cart</a></div>
                  <div class="column"><a id="chek" class="btn btn-sm btn-block btn-success" href="">Checkout</a></div>
                </div></div>
            </div>';?>
            <?php endif ?>
          </div>
        </div>
      </div>
    </header>