<?= $this->insert('overall/header') ?>
  <!-- Body-->
  <body>
    <?= $this->insert('overall/navmovil')?>
    <?= $this->insert('overall/topnav')?>
    <!-- Off-Canvas Wrapper-->
    <div class="offcanvas-wrapper">
      <!-- Page Content-->
        <div class="padding-top-1x mt-2 text-center">
          <div class="col-md-12">
            <form rol="form" class="login-box" enctype="application/x-www-form-urlencoded" id="login_form">
              <div class="row margin-bottom-1x">
                <div class="col-xl-4 col-md-6 col-sm-4"><a class="btn btn-sm btn-block facebook-btn" href="#"><i class="socicon-facebook"></i>&nbsp;Sesion con Facebook</a></div>
                <div class="col-xl-4 col-md-6 col-sm-4"><a class="btn btn-sm btn-block twitter-btn" href="#"><i class="socicon-twitter"></i>&nbsp;Sesion Twitter</a></div>
                <div class="col-xl-4 col-md-6 col-sm-4"><a class="btn btn-sm btn-block google-btn" href="#"><i class="socicon-googleplus"></i>&nbsp;Sesion Google+</a></div>
              </div>
              <h4 class="margin-bottom-1x">Ó inicia sesion con tus datos</h4>
               <div class="alert hide" id="ajax_login"></div>
              <div class="form-group input-group">
                <input class="form-control" type="email" name="user" placeholder="Correo" required><span class="input-group-addon"><i class="icon-mail"></i></span>
              </div>
              <div class="form-group input-group">
                <input class="form-control" type="password" name="pass" placeholder="Contraseña" required><span class="input-group-addon"><i class="icon-lock"></i></span>
              </div>
              <div class="d-flex flex-wrap justify-content-between padding-bottom-1x">
                <label class="custom-control custom-checkbox">
                  <input class="custom-control-input" type="checkbox" checked><span class="custom-control-indicator"></span><span class="custom-control-description">Recordar</span>
                </label><a href="#" data-toggle="modal" data-dismiss="modal" data-target="#lost_pass">¿Contraseña Perdida?</a>
              </div>
              <div class="text-center text-sm-right">
                <button type="button" id="login" class="btn btn-sm btn-primary">Iniciar Sesión</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <?= $this->insert('overall/inner_footer')?>
    <?= $this->insert('overall/footer')?>
  </body>

</html>